from typing import Protocol

from src.ui.views.base_view import BaseView

class HomeView(BaseView, Protocol):
    def get_rut_input(self) -> str: ...
    def clear_outputs(self) -> None: ...
    def set_patient_data(self, nombre: str, rut: str, telefono: str, correo: str) -> None: ...
    def set_agenda_data(self, fecha: str, hora: str, estado: str) -> None: ...
    def show_patient_not_found(self) -> None: ...
    def clear_rut_input(self) -> None: ...
